DROP TABLE IF EXISTS SERVICE_REQUEST;

DROP TABLE IF EXISTS SERVICE_CATEGORY;

DROP TABLE IF EXISTS OWNER;

DROP TABLE IF EXISTS CONDO_UNIT;

DROP TABLE IF EXISTS LOCATION;

DROP TABLE IF EXISTS RENTAL_AGREEMENTS;

DROP TABLE IF EXISTS PROPERTIES;

DROP TABLE IF EXISTS RENTERS;
